import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

test('squad builder is routed, navigable, and wired to owned cards', () => {
  const appSource = readFileSync('src/App.tsx', 'utf8');
  const navigationSource = readFileSync('src/config/navigation.ts', 'utf8');
  const pageSource = readFileSync('src/pages/SquadBuilder.tsx', 'utf8');
  const resourcesSource = readFileSync('src/i18n/resources.ts', 'utf8');

  assert.match(appSource, /lazy\(\(\) => import\('\.\/pages\/SquadBuilder'\)\)/);
  assert.match(appSource, /path="\/squad-builder"/);
  assert.match(navigationSource, /to: '\/squad-builder'/);
  assert.match(navigationSource, /nav\.items\.squadBuilder/);
  assert.match(navigationSource, /Shield/);

  assert.match(pageSource, /AppShell/);
  assert.match(pageSource, /listCurrentUserOwnedCards/);
  assert.match(pageSource, /listSavedSquadFormations/);
  assert.match(pageSource, /createSavedSquadFormation/);
  assert.match(pageSource, /updateSavedSquadFormation/);
  assert.match(pageSource, /deleteSavedSquadFormation/);
  assert.match(pageSource, /pruneAssignmentsForOwnedCards/);
  assert.match(pageSource, /SquadPitchBuilder/);
  const builderSource = readFileSync('src/components/squad/SquadPitchBuilder.tsx', 'utf8');
  assert.match(builderSource, /getPlayerCardDisplayImageUrl/);
  assert.match(builderSource, /\.\.\/\.\.\/\.\.\/squadbuilder_empty_slot\.svg/);
  assert.match(builderSource, /assignCardToSlot/);
  assert.match(builderSource, /getAssignedOwnedCardIds/);
  assert.match(pageSource, /appPages\.squadBuilder/);
  assert.match(builderSource, /PLAYER_PAGE_SIZE = 12/);
  assert.match(builderSource, /type PositionFilter = 'all' \| string/);
  assert.match(builderSource, /type PlayerSort = 'position' \| 'rarity'/);
  assert.match(builderSource, /RARITY_ORDER/);
  assert.match(builderSource, /rarityRank/);
  assert.match(builderSource, /POSITION_FILTERS/);
  assert.match(builderSource, /positionFilter/);
  assert.match(builderSource, /playerSort/);
  assert.match(builderSource, /grid h-24 w-full grid-cols-\[64px_minmax\(0,1fr\)_44px\]/);
  assert.match(builderSource, /groupedOwnedCards/);
  assert.match(builderSource, /duplicateCount/);
  assert.match(builderSource, /paginatedOwnedCards/);
  assert.match(builderSource, /max-h-\[520px\].*overflow-y-auto/);
  assert.match(builderSource, /aspect-\[12\/13\]/);
  assert.match(builderSource, /min-h-\[620px\]/);
  assert.match(builderSource, /max-w-\[820px\]/);
  assert.match(builderSource, /w-\[96px\].*sm:w-\[132px\]/);
  assert.match(builderSource, /event\.stopPropagation\(\)/);
  assert.match(builderSource, /setPositionFilter\(slot\.label\);/);
  assert.match(builderSource, /showAnimatedCards/);
  assert.match(builderSource, /setShowAnimatedCards\(\(current\) => !current\)/);
  assert.match(builderSource, /getPlayerCardDisplayImageUrl\(card\.player_cards, showAnimatedCards \|\| card\.is_gif_upgrade\)/);
  assert.match(builderSource, /h-32 w-32.*sm:h-40 sm:w-40/);
  assert.match(builderSource, /drop-shadow-\[4px_4px_0_rgba\(0,0,0,0\.35\)\]/);
  assert.doesNotMatch(builderSource, /radial-gradient/);
  assert.doesNotMatch(builderSource, /rounded-full border-4 border-white\/70/);

  assert.match(resourcesSource, /squadBuilder: 'Squad Builder'/);
  assert.match(resourcesSource, /animationOn: 'Animation on'/);
  assert.match(resourcesSource, /animationOff: 'Animation off'/);
  assert.match(resourcesSource, /squadBuilderShort: 'Squad'/);
  assert.match(resourcesSource, /squadBuilder: 'Xếp đội hình'/);
  assert.match(resourcesSource, /animationOn: 'Bật animation'/);
  assert.match(resourcesSource, /animationOff: 'Tắt animation'/);
});
